### ISSUE TITLE
Smartdebit Sync - Not pulling collection report

### ISSUE THREAD

**Issue by rajeshrhino** [mattwire/org.civicrm.smartdebit#13]
@mattwire The collection report is available in Smart Debit only after 3 days (Example: The collection report for 15th Jan 2018 will be available only on 18th Jan 2018). But Smartdebit sync scheduled job looks for a report for the current date and the API call always returns error.

So we will need to backtrack few days and get the collection reports and then process the payments.

We have made the tweaks and created PR https://github.com/mattwire/org.civicrm.smartdebit/pull/12

**Comment by mattwire** [comment]
Thanks. Incorporated into release 1.21
