### ISSUE TITLE
Default days difference to check first payment does not work for some cases

### ISSUE THREAD

**Issue by rajeshrhino** [mattwire/org.civicrm.smartdebit#15]
**SD settings:**
- Yearly DD
- Collection Day: 21st of every month

**Workflow:**
- Member Joins on 13th March 2018
- Initial contribution created with received date as 13th March 2018
- First Payment in SD will be 21st April 2018 (Payment cannot be on 21st March 2018, because of 14 days notification period)
- SD Sync done on 21st April 2018

**Issue**
- New contribution is created and membership renewed for another year, as 30 days difference to get first contribution will not work in this case

**Solution**
Make days difference as a configurable settings, so that we can override the default days difference, if needed. Overriding days difference as 60 days will work for the above case

**PR**
We have made the changes and created PR https://github.com/mattwire/org.civicrm.smartdebit/pull/14
Please review and merge.

**Comment by mattwire** [comment]
Hi @rajeshrhino Thanks for the bug report and explanation. Do we really need to add extra settings for this or can we just improve the default behaviour so it works in all situations?

By the way, I've started adding a basic test suite to the smartdebit extension.  I'd like to see unit tests implemented around the "days difference" before we make any changes there.

**Comment by mattwire** [comment]
Closing as no response from reporter
