### ISSUE TITLE
Error when next collection date is before the minimum collection interval.

### ISSUE THREAD

**Issue by verblet** [mattwire/org.civicrm.smartdebit#18]
using Smart Debit extension v1.22 & CiviCRM v5.0.0 on Drupal v7.58

Steps to reproduce:
- Set the collection date to be the 1st of the month
- Set the collcetion interval to be 10 days
- Set up a membership payment page 
- Fill out the membership form < 10 days before the 1st of the next month (e.g. on 20th April)
- Get the error "Start date must be on or after 01/06/2018"

I assume the date being passed to SmartDebit is the first of the *next* month when it should be the 1st of the next available month (in this case 1st June)

Is this a setup/config problem or a bug?

**Comment by verblet** [comment]
FYI changing the collection interval to 15 days fixed it but I am not sure if I have just met an edge case here by testing exactly 10 days before the 1st of the next month.

**Comment by mattwire** [comment]
Hi, looks like you may have hit a bug.  I've just started adding a test suite around this kind of stuff because it's really hard to test thoroughly!  Do you have time to investigate any further?  Eg. find out what value is actually being passed to smartdebit - enabling debug logging in the civicrm smartdebit settings should give you this information in the Civi log I think.

**Comment by verblet** [comment]
Yes I can look into this on Monday.

**Comment by mattwire** [comment]
@verblet did you make any progress on this?

**Comment by mattwire** [comment]
Closing as no response from reporter

**Comment by michaelmcandrew** [comment]
hey @verblet and @mattwire - we're having a similar issue... will add a bit more info here once I have experimented a bit...

**Comment by michaelmcandrew** [comment]
Here's my experience:
The extension was configured with a collection interval of 11 and collection dates of 1 and 15.
The payment processed on 21st May
Smart debit received a date of 1 June but complained that "Start date must be on or after 15/06/2019".

**Comment by mattwire** [comment]
Resolved in 1.32
