### ISSUE TITLE
SmartDebit import not renewing all memberships

### ISSUE THREAD

**Issue by verblet** [mattwire/org.civicrm.smartdebit#19]
I work for an organisation that has about a few thousand membership payments coming in to CiviCRM every month via SmartDebit.

However when payments are synced some memberships are not being renewed.

I've checked that the membership is linked to the recurring payment.

Here is the results of an API call on a failing membership (that pays yearly). Note that the 'next_sched_contribution' date is still 2018 even though the modified_date has been set to 2018 and a payment was taken in 2018.

I also have logs from the SmartDebit import that I can attach

```
MEMBERSHIP
            "id": "13581",
            "contact_id": "22296",
            "membership_type_id": "11",
            "join_date": "2011-01-24",
            "start_date": "2016-03-01",
         -->"end_date": "2018-02-28",
            "source": "Direct Debit",
            "status_id": "3",
            "is_test": "0",
            "is_pay_later": "0",
         -->"contribution_recur_id": "1592",
            "membership_name": "Standard Yearly Membership",

RECURRING CONTRIBUTION
         -->"id": "1592",
            "contact_id": "22296",
            "amount": "72.00",
            "currency": "GBP",
            "frequency_unit": "year",
            "frequency_interval": "1",
            "start_date": "2015-03-01 00:00:00",
            "create_date": "2015-03-01 00:00:00",
         -->"modified_date": "2018-04-04 17:59:40",
            "trxn_id": "iba2229",
            "invoice_id": "[XXXXXXXXXX]",
            "contribution_status_id": "5",
            "is_test": "0",
            "cycle_day": "1",
            "next_sched_contribution_date": "2018-03-19 13:40:04",
            "failure_count": "0",
            "auto_renew": "1",
            "payment_processor_id": "3",
            "financial_type_id": "2",
            "payment_instrument_id": "7",
            "is_email_receipt": "0",
            "contribution_type_id": "2",
         -->"next_sched_contribution": "2018-03-19 13:40:04"

INDIVIDUAL CONTRIBUTION
            "contact_id": "22296",
            "contribution_id": "49702",
            "currency": "GBP",
            "payment_instrument": "Direct Debit",
            "payment_instrument_id": "7",
         -->"receive_date": "2018-03-01 00:00:00",
            "non_deductible_amount": "0.00",
            "total_amount": "72.00",
            "fee_amount": "0.00",
            "net_amount": "72.00",
            "trxn_id": "[XXXXXXXXXX]",
            "invoice_id": "",
            "invoice_number": "",
            "cancel_date": "",
            "cancel_reason": "",
            "receipt_date": "",
            "thankyou_date": "",
            "contribution_source": "Smart Debit Import",
            "amount_level": "",
         -->"contribution_recur_id": "1592",
            "is_test": "0",
            "is_pay_later": "0",
            "contribution_status": "Completed",
            "contribution_status_id": "1",
            "contribution_check_number": "",
            "contribution_campaign_id": "",
            "check_number": "",
            "instrument_id": "7",
            "id": "49702"
```

**Comment by mattwire** [comment]
@verblet Did you make any progress with this?

**Comment by verblet** [comment]
No, unfortunately I've not had time (we've been manually updating these memberships every month with a search).

I'm no nearer figuring out why only some of these contributions are failing to trigger a status change. I will need to test it further with debug on and, tbh, I've not had the time.

I will put time in next week to take a look. What do you need from me? Is there a debug setting I can turn on other than CiviCRMs core one?

**Comment by mattwire** [comment]
There's been quite a few changes in the next version of the smartdebit extension (1.24) - not yet released.  One of them fixes setting the next_sched_contribution date correctly.

However, the membership renewal issue will be something in core, and has been reported by a number of different organisations but none of them have got back to me with any more information about what is actually failing.
* Can you put a dump of the membershiptype here as well? (like above, from the API for the membership type that is failing).
* Do you know when you ran the sync from smartdebit that actually updated the contribution (the receive_date is set to the value given by smartdebit)?
* What are your membership status rules?

I'm wondering if there could be some interaction between membership end_date/status rules and the payment coming in when it's in a certain state.

**Comment by mattwire** [comment]
No response from submitter
