### ISSUE TITLE
Manual sync inconsistencies

### ISSUE THREAD

**Issue by mattwire** [mattwire/org.civicrm.smartdebit#2]
Tested by finding a contact with a successful Smart Debit record and a contribution_recur record in Civi. Changed the status of their contribution to Cancelled, then tried manual sync. Expect contribution status to be updated to Completed.

Noted that "Manual Sync" behaves a littles differently from "Run Sync Task".

Manual Sync, with no date entered so processing last 3 months, says 14 contributions already processed, 713 not matched to contacts, "As there are no matching contacts you cannot import any transactions." There is no option to proceed, just a Back button.

However Run Sync Task goes ahead, displaying a progress bar with e.g. "Executed: Syncing smart debit collection reports - contacts 390 of 1018". In the Civi log file, we get:

Jun 26 15:44:30  [info] Smartdebit cron: Retrieving Daily Collection Report.
Jun 26 15:44:30  [info] Smartdebit Sync: Retrieving Smart Debit Payer Contact Details.
Jun 26 15:44:51  [info] Smartdebit Sync: Retrieving AUDDIS reports.
Jun 26 15:44:51  [info] Smartdebit Sync: Retrieving ARUDD reports.

whereas Manual Sync admin says, "CiviCRM will attempt to retrieve AUDDIS and ARUDD records for a -3 month period ending with the date you specify here." I.e. looks like Manual Sync doesn't do Daily Collection Report or Smart Debit Payer Contact Details. Would be good to clarify this in admin + docs so that people can understand what to do when.

Result: after Run Sync Task, the tested contribution was correctly updated back to Completed.

**Comment by mattwire** [comment]
There is now only "Manual Sync" option in navigation menu. https://github.com/mattwire/uk.co.vedaconsulting.smartdebit/commit/6b6d5f3bb121dcd609eea88438d001cc00bb596e

**Comment by davejenx** [comment]
Re-tested the same scenario. The altered contribution falls in the last 3 months.

Noted that the Manual Sync option has this help text:
"CiviCRM will attempt to retrieve AUDDIS and ARUDD records for a -3 month period ending with the date you specify here.
This should not normally be necessary as the collection reports are retrieved daily by the SmartDebit scheduled job. If you specify a date here the collection report data will be refreshed and -3 month of data re-synced from SmartDebit (this will take a few minutes when you submit). If you don't specify a date the cached data will not be modified.
If you are importing latest payments (up to -3 month old) you should not need to enter a date here. "

So the date field has 2 roles IIUC: setting end date and controlling whether collection reports are sync'd, giving 3 scenarios:
- past date entered: sync AUDDIS + ARUDD + collection reports for 3 months ending on specified date
- today's date entered: sync AUDDIS + ARUDD + collection reports for 3 months ending today
- no date entered: sync AUDDIS + ARUDD only for 3 months ending today

First, tested without entering a date.
- No AUDDIS dates found for selected date range.
- No ARUDD dates found for selected date range.
(Should these say "No AUDDIS/ARUDD records found..." ?)
Clicked Continue
- Summary showing 0 rejected contribution in AUDDIS/ARUDD, 2 Contribution already processed, 8 Contribution not matched to contacts.
The contribution that I manually updated to Cancelled wasn't among these.
Clicked Continue & confirmed
- Summary showing 2 Valid Contribution(s) synchronised with CiviCRM (with different transaction ids), 2 Failed Contribution(s) synchronised with CiviCRM (with the same transaction id). I'm not sure how these numbers fit with the ones shown in the summary before sync, but that may be my misunderstanding.
The contribution that I manually updated to Cancelled wasn't among them.

Second, tested entering today's date.
- No AUDDIS dates found for selected date range.
- No ARUDD dates found for selected date range.
Clicked Continue.
- Summary showing 0 rejected contribution in AUDDIS/ARUDD, 4 Contribution already processed, 47 Contribution not matched to contacts, 1 Contribution matched to contacts.
The contribution that I manually updated to Cancelled was listed among the Contributions already processed.
Clicked Continue & confirmed
- Summary showing 5 Valid Contribution(s) synchronised with CiviCRM, including the one I manually altered; 2 Failed Contribution(s) synchronised with CiviCRM. Again I'm not sure how these numbers fit with the ones shown in the summary before sync, but that may be my misunderstanding.
The contribution that I manually updated to Cancelled was changed to Completed.

I think that's good. I initially found the date field's dual role confusing but I believe the help text does accurately describe how it operates. As I mentioned, some of the numbers in summaries before & after sync didn't seem to tally but I may have misunderstood what these represented.
