### ISSUE TITLE
SQL syntax error at install

### ISSUE THREAD

**Issue by Czollli** [mattwire/org.civicrm.smartdebit#20]
version 1.24
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

** You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONSTRAINT UC_Collection UNIQUE (transaction_id, amount, receive_date)

version 1.23
Installed fine

Thanks for taking a look

**Comment by mattwire** [comment]
Sorry, should be fixed in https://github.com/mattwire/org.civicrm.smartdebit/commit/52d08225a10147a2dc6bc21bf82f06be332ac7ec

**Comment by mattwire** [comment]
This only affects new installs of 1.24.

**Comment by Czollli** [comment]
Thank you,
I have just upgraded from 1.23.

**Comment by mattwire** [comment]
Thanks for reporting :-) I've release 1.24.1 for new installs
