### ISSUE TITLE
Gocardless support

### ISSUE THREAD

**Issue by axaak** [mattwire/org.civicrm.smartdebit#25]
Hi,
thanks for your work on this code.

I followed the link here from the old Veda Consulting extension which had Gocardless support.  I'm guessing this extension only provides support for Smart Debit not Gocardless?

Many thanks for your time,
axaak

**Comment by mattwire** [comment]
@axaak Try this: https://github.com/artfulrobot/uk.artfulrobot.civicrm.gocardless
