### ISSUE TITLE
Smart Debit import failing (duplicate payment IDs?)

### ISSUE THREAD

**Issue by verblet** [mattwire/org.civicrm.smartdebit#27]
Smart Debit imports (both auto sync and manual sync) are failing.

SmartDebit: 1.29 
CiviCRM: 5.7.0
Drupal: 7.59

There is a failure in the middle of the sync while processing an individual record, but even when that is skipped none of the contributions are imported.

An example from the log shows this:

> Jan 22 12:02:12  [debug] Smartdebit processCollection: $contribution=Array
> (
>     [contact_id] => 119428
>     [contribution_recur_id] => 3400
>     [total_amount] => 3.00
>     [invoice_id] => ac4a9a6c5e68be1fde2634b6cef4308f
>     [trxn_id] => 00031285/20190101000000
>     [financial_type_id] => 2
>     [payment_instrument_id] => 7
>     [receive_date] => **20190101000000**
>     [is_email_receipt] => 
>     [id] => **63391**
>     [source] => [SDCR] Online Contribution: Join the Scottish Greens
> )
> 
> 
> Jan 22 12:02:12  [debug] Smartdebit processCollection: success recurpayment (recur:3400)

The Contribution ID is given as 63391, but that ID already exists in CiviCRM, associated to an earlier payment by that same contact:

> {
>     "is_error": 0,
>     "version": 3,
>     "count": 1,
>     "id": 63391,
>     "values": [
>         {
>             "contact_id": "119428",
>             "id": "**63391**",
>             "contribution_id": "63391",
>             "receive_date": "**2018-10-01 00:00:00**",
>             "contribution_recur_id": "3400"
>         }
>     ]
> }

This is the case for a handful of log records I checked.

What could be causing this?

**Comment by verblet** [comment]
I realise I did not paste the error that happened in the middle of the sync:

> 
> Jan 22 11:54:33  [info] Running task: Processed Smartdebit collections: 1650 to 1660 of 3542
> 
> Jan 22 11:54:33  [info] $CRM_Queue_Page_AJAX_runNext_error = CRM_Core_Exception: "Count of headers does not match count of values returned from Smartdebit API for Mandate"
> #0 /srv/members/public/sites/default/files/civicrm/extensions/org.civicrm.smartdebit/CRM/Smartdebit/Mandates.php(354): CRM_Smartdebit_Mandates::save((Array:1), "CSV")
> #1 /srv/members/public/sites/default/files/civicrm/extensions/org.civicrm.smartdebit/CRM/Smartdebit/Mandates.php(55): CRM_Smartdebit_Mandates::retrieve((Array:1))
> #2 /srv/members/public/sites/default/files/civicrm/extensions/org.civicrm.smartdebit/CRM/Smartdebit/Sync.php(282): CRM_Smartdebit_Mandates::getbyReference((Array:1))
> #3 /srv/members/public/sites/default/files/civicrm/extensions/org.civicrm.smartdebit/CRM/Smartdebit/Sync.php(258): CRM_Smartdebit_Sync::processCollection("edu3216", "2018-12-01", "13.00", 0)
> #4 [internal function](): CRM_Smartdebit_Sync::syncSmartdebitCollectionReports(Object(CRM_Queue_TaskContext), 1650, 10)
> #5 /srv/members/public/sites/all/modules/civicrm/CRM/Queue/Task.php(88): call_user_func_array((Array:2), (Array:3))
> #6 /srv/members/public/sites/all/modules/civicrm/CRM/Queue/Runner.php(214): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
> #7 /srv/members/public/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE)
> #8 /srv/members/public/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}()
> #9 /srv/members/public/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure))
> #10 [internal function](): CRM_Queue_Page_AJAX::runNext()
> #11 /srv/members/public/sites/all/modules/civicrm/CRM/Core/Invoke.php(275): call_user_func((Array:2))
> #12 /srv/members/public/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))
> #13 /srv/members/public/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
> #14 /srv/members/public/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:4))
> #15 [internal function](): civicrm_invoke("queue", "ajax", "runNext")
> #16 /srv/members/public/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:3))
> #17 /srv/members/public/index.php(21): menu_execute_active_handler()
> #18 {main}

**Comment by mattwire** [comment]
@verblet Thanks for reporting.  That error is triggered here: https://github.com/mattwire/org.civicrm.smartdebit/blob/master/CRM/Smartdebit/Mandates.php#L192 and the code comment explains why it might happen.  I agree that it shouldn't stop the whole sync process though... are you able to investigate a bit further and see if you can work out why it's going wrong based on that bit of code?

**Comment by verblet** [comment]
Looking into this further today and will update you on my progress

**Comment by verblet** [comment]
Result: one of the cells (payer_reference) contained a comma that is parsed as a column separator:
`Â£3 Gla,Â£10 H`

I imagine this string should be cleaned first?

Debug of csv variables:

> Jan 24 15:58:03  [debug] Smartdebit processCollection: $csvHeaders=Array(
>     [0] => payer_reference
>     [1] => reference_number
>     [2] => frequency_type
>     [3] => frequency_factor
>     [4] => start_date
>     [5] => title
>     [6] => first_name
>     [7] => last_name
>     [8] => email_address
>     [9] => address_1
>     [10] => address_2
>     [11] => address_3
>     [12] => town
>     [13] => county
>     [14] => postcode
>     [15] => regular_amount
>     [16] => first_amount
>     [17] => current_state
>     [18] => support_gift_aid
> )
> 
> Jan 24 15:58:03  [debug] Smartdebit processCollection: $csvValues=Array
> (
>     [0] => £3 Gla
>     [1] => £10 H
>     [2] => ed*****
>     [3] => M
>     [4] => 1
>     [5] => 2015/11/01
>     [6] => 
>     [7] => E*****
>     [8] => D*****
>     [9] => *****@googlemail.com
>     [10] => ADDRESS
>     [11] => 
>     [12] => 
>     [13] => Glasgow
>     [14] => 
>     [15] => POSTCODE
>     [16] => 13.00
>     [17] => 
>     [18] => 10
>     [19] => false
> )
> 

FYI I am still unsure how the Contribution ID is being set as an older existing ID?

**Comment by mattwire** [comment]
@verblet That comma will definitely break it!  As it's CSV data being sent by the Smartdebit API it needs fixing (just update the payer_reference to remove the comma) at the Smartdebit end.

The contribution ID should not matter in this instance as it will call repeatTransaction and use the trxn_id to generate a new contribution.

**Comment by verblet** [comment]
I'm removing the comma at smart debit end and re-running the import, fingers crossed!

**Comment by verblet** [comment]
The import has finished but no contributions have been added.

I've spotted this error:

> Jan 25 09:57:08  [debug] Smartdebit processCollection: $contribution=Array
> (
>     [contact_id] => 21551
>     [contribution_recur_id] => 1161
>     [total_amount] => 3.00
>     [invoice_id] => xxxxxxxx
>     [trxn_id] => xxxxxx
>     [financial_type_id] => 2
>     [payment_instrument_id] => 7
>     [receive_date] => 20190101000000
>     [is_email_receipt] => 
>     [id] => 65365
>     [source] => [SDCR]
> )
> Jan 25 09:57:08  [debug] Smartdebit processCollection: success recurpayment (recur:1161)
> **Jan 25 09:57:08  [error] Smartdebit repeatTransaction: Missing mandatory parameter: 0**

That error looks like it is coming from core, not the extension, is that right?

**Comment by mattwire** [comment]
The error is triggered from Smartdebit (`CRM/Smartdebit/Sync.php line 470`) but not sure why it would be doing that - haven't seen this issue elsewhere.

**Comment by mattwire** [comment]
@verblet Please can you test latest master (will become 1.30 if it works). I just hit this on another site and have pushed two fixes.

**Comment by verblet** [comment]
@mattwire this works, contributions are now being added on my test server

EDIT: The manual import is pausing every so often. Last log messages (differences in arrays highlighted in bold):

>Smartdebit recurs don't match: Original: Array
>( 
>     [id] => 1060
>     [contact_id] => 40110
>     [amount] => 5.00
>     [currency] => GBP
>     [frequency_unit] => year
>     [frequency_interval] => 1
>     [start_date] => 2017-12-01 00:00:00
>     [create_date] => 2016-10-21 12:03:29
>     [modified_date] => 2019-01-28 13:55:14
>     [processor_id] => xxx
>     [trxn_id] => xxx
>     [invoice_id] => xxx
>     [contribution_status_id] => 5
>     [is_test] => 0
>     [cycle_day] => 1
>     **[next_sched_contribution_date] => 2019-12-01 00:00:00**
>     [failure_count] => 0
>     [auto_renew] => 1
>     [payment_processor_id] => 3
>     [financial_type_id] => 2
>     [payment_instrument_id] => 7
>     [is_email_receipt] => 0
>     [contribution_type_id] => 2
>     [next_sched_contribution] => 2019-12-01 00:00:00
> )
>  New: Array
> (
>     [id] => 1060
>     [contact_id] => 40110
>     [amount] => 5.00
>     [currency] => GBP
>     [frequency_unit] => year
>     [frequency_interval] => 1
>     [start_date] => 2017-12-01 00:00:00
>     [create_date] => 2016-10-21 12:03:29
>     [modified_date] => 2019-01-28 13:55:14
>     [processor_id] => xxx
>     [trxn_id] => xxx
>     [invoice_id] => xxx
>     [contribution_status_id] => 5
>     [is_test] => 0
>     [cycle_day] => 1
>     **[next_sched_contribution_date] => 20191201**
>     [failure_count] => 0
>     [auto_renew] => 1
>     [payment_processor_id] => 3
>     [financial_type_id] => 2
>     [payment_instrument_id] => 7
>     [is_email_receipt] => 0
>     [contribution_type_id] => 2
>     [next_sched_contribution] => 2019-12-01 00:00:00
> )
>
> Jan 28 13:55:16  [error] Smartdebit API: 503: Unknown Error Request URL: https://secure.ddprocessing.co.uk/api/data/dump?query[service_user][pslid]=xxxx&query[report_format]=CSV&query[include_header]=false&query[reference_number]=xxx

**Comment by verblet** [comment]
While the progress bar pauses, the import does complete successfully. I consider this fixed. Thank you!
