### ISSUE TITLE
Reconciliation with no amount

### ISSUE THREAD

**Issue by mattwire** [mattwire/org.civicrm.smartdebit#3]
Tested as follows: find a Customer ID that doesn't match an existing contribution_recur.

"Fix Me" link lets me manually select contact via autocomplete field, then membership & recurring contribution (only option was to create new recurring).

After reconciliation:

I got this error in UI:
Error linking membership (41354) to recurring contribution () Missing params[contribution_recur_id]
The error bubble disappeared after a few seconds, maybe good to make it persist.

Civi log has this error:
Jun 26 16:48:55  [info] Smartdebit createRecurContribution: ERROR must specify amount!

Presumably the lack of Default Amount / First Amount in SD caused the contribution_recur not to be created, subsequently leading to the error shown in UI.
Perhaps the reconciliation UI shouldn't offer to fix those where amount = 0? Which is all 632 listed under "With No Contact in CiviCRM and no Amount".

**Comment by mattwire** [comment]
Should be resolved in https://github.com/mattwire/uk.co.vedaconsulting.smartdebit/commit/bdc4298e9b63367b29c7cb42e76721f1dda7c36e

**Comment by davejenx** [comment]
Verified that "Fix Me" link now does not display when there is no Amount. :-)
