### ISSUE TITLE
Membership/contribution status issues when not auto-renew

### ISSUE THREAD

**Issue by mattwire** [mattwire/org.civicrm.smartdebit#4]
1 membership:
- Test membership, so doesn't show in Memberships tab (inconsistency in Civi there, as test contributions do show)
I guess we should raise a JIRA for that. 
- Status = New (see above re status),
- Auto-renew = No - should this have been set to Yes in membership type config? Ah, you say above that you've configured "Affiliate by DD" as auto-renew required but the contrib page you linked to is for Associate by DD, whose membership type isn't auto-renew.
MJW: Oops.. 
- Join date: May 22nd, 2017
- Start Date: January 1st, 2017
- End date: December 31st, 2017

1 contribution:
- Test contribution
- Status: completed (expected pending, as no payment taken yet?)
- contribution_recur_id: null (I assume due to membership type config not having auto-renew)
MJW: DD doesn't really support non-recurring payments, I try and fudge it by setting an end date with smartdebit but I guess we might not be putting the right data into Civi for this case. 

0 contribution_recur: 
- (I assume due to membership type config not having auto-renew)

In secure.ddprocessing.co.uk (test):
DD mandate created:
- Frequency: Variable Amount, Fixed Frequency (Y)
- Amount: £65
- Start date: 15 Jun 2017
- Final date: 21 Jun 2017

So it looks like I've accidentally tested single payment. The unexpected results were contribution status completed & membership status new, expected pending for both.

**Comment by mattwire** [comment]
Should be resolved in https://github.com/mattwire/uk.co.vedaconsulting.smartdebit/commit/9cba0025a7915ff5d0d0e887d6126409b0af8e97
A recurring contribution with a single installment is created, contribution is created in state "pending".

**Comment by davejenx** [comment]
Re-tested, this time with a live transaction due to a local issue with test mode.

Confirm that a recurring contribution with a single installment is created (in status Pending), contribution is created in state "pending".
