### ISSUE TITLE
Reconciliation should use smartdebit audit log to set created date for recurring contribution

### ISSUE THREAD

**Issue by mattwire** [mattwire/org.civicrm.smartdebit#5]
The date the instruction was created can be retrieved via the audit API.  This is not the same as the start date which is the date the first payment should be taken.  It gives a clearer audit trail in CiviCRM if the created date is set to the actual created date instead of whatever date it was reconciled.

**Comment by mattwire** [comment]
Implemented in https://github.com/mattwire/uk.co.vedaconsulting.smartdebit/commit/933a65f31a42ae90c8ae249242557adff48f0bc5

**Comment by davejenx** [comment]
Verified that after creating civicrm_contribution_recur via reconciliation Fix Me link, create_date was set to the created date shown in SD admin / audit details.
