### ISSUE TITLE
Proceeding to the next step with validation errors

### ISSUE THREAD

**Issue by krishgopi** [mattwire/org.civicrm.smartdebit#7]
Hi @mattwire  

Tested the extension & contribution form allows users to continue to the next step & proceed with making contribution regardless of validation errors from smart debit. 

![validation errors](https://user-images.githubusercontent.com/13120005/29214697-40483102-7ea0-11e7-8aa8-bf3e8c99eebe.PNG)

regards
Gopi
(Veda Consulting)

**Comment by mattwire** [comment]
Ok, I'm guessing that the errors are not being passed back up properly.  There is still some of the original code in play here. The $errors array should be being set in this function (https://github.com/mattwire/org.civicrm.smartdebit/blob/master/CRM/Core/Payment/Smartdebit.php#L133) by validatePayment() I think.

**Comment by mattwire** [comment]
Do you have time to look at a fix?

**Comment by mattwire** [comment]
@krishgopi Hi, should be fixed now in 1.3 release - can you confirm please?

**Comment by krishgopi** [comment]
Hi @mattwire ,

Apologies for the delay in getting back to you. Tested 1.3 release and the validations are working fine now.

Thanks

**Comment by mattwire** [comment]
Great, thankyou!
