### ISSUE TITLE
Membership renewal on new payments imported by sync

### ISSUE THREAD

**Issue by deepak-srivastava** [mattwire/org.civicrm.smartdebit#8]
I'm raising it because we unable to see membership renewal happening for newly created payments through sync, even though the membership is linked to recurring contribution record and set to auto renew.

I see that the extension is using [contribution](https://github.com/mattwire/org.civicrm.smartdebit/blob/master/CRM/Smartdebit/Base.php#L653) and [contribution recur](https://github.com/mattwire/org.civicrm.smartdebit/blob/master/CRM/Smartdebit/Base.php#L566) create apis for new payments. 

The civicrm core (contribution/recur) create apis do not seem to (or designed to) handle membership renewals. 

It seems the way civi renews related memberships is through CRM_Contribute_BAO_Contribution::completeOrder() which is mainly called by payment processor IPNs (recurring payments), but isn't triggered by contribution/recur create apis. There is [separate api](https://github.com/civicrm/civicrm-core/blob/master/api/v3/Contribution.php#L521) as well which calls completeOrder() method.

My question is - if the extension is taking care of renewals, where is it happening in the extension or civi core?

**Comment by mattwire** [comment]
Hmm, I thought it did, but maybe was mistaken.  Can you test the membership_renewal branch and let me know if that works?  I've implemented the Contribution.completetransaction API call there.

**Comment by mattwire** [comment]
@deepak-srivastava Any feedback?
